import Foundation

/// `~/.perch/todo.md`: a read-only view of the queue, rendered by perchd after every change.
/// One-way only — edits are overwritten; new items go through `inbox.md` or the CLI.
public enum MirrorRenderer {
    public static let header = "<!-- Generated by perchd. Read-only: rewritten on every change. To add a task, append \"- [ ] title\" to inbox.md. -->"

    /// `items` should be the active items (open, waiting); they are rendered in queue order.
    public static func render(_ items: [Item], now: Date = Date(), calendar: Calendar = .current) -> String {
        let active = items.filter { $0.status == .open || $0.status == .waiting }.queueOrdered(now: now, calendar: calendar)
        let waiting = active.filter { $0.kind == .request || ($0.kind != .notice && $0.status == .waiting) }
        let todo = active.filter { $0.kind == .task && $0.status == .open }
        let notices = active.filter { $0.kind == .notice }

        var out = [header, "", "# Perch", ""]
        func section(_ title: String, _ items: [Item], checkbox: Bool) {
            guard !items.isEmpty else { return }
            out.append("## \(title)")
            out.append("")
            out += items.map { line($0, checkbox: checkbox, calendar: calendar) }
            out.append("")
        }
        section("Waiting on you", waiting, checkbox: true)
        section("To do", todo, checkbox: true)
        section("Notices", notices, checkbox: false)
        if active.isEmpty {
            out += ["Nothing waiting.", ""]
        }
        return out.joined(separator: "\n")
    }

    static func line(_ item: Item, checkbox: Bool, calendar: Calendar) -> String {
        var details: [String] = []
        if item.kind == .request { details.append("request") }
        if let due = item.dueAt { details.append("due \(format(due, calendar: calendar))") }
        details.append(item.source)
        if let link = item.link { details.append(link) }
        details.append("`\(item.id)`")
        let title = item.title.replacingOccurrences(of: "\n", with: " ")
        return "- \(checkbox ? "[ ] " : "")\(title) — \(details.joined(separator: " · "))"
    }

    private static func format(_ date: Date, calendar: Calendar) -> String {
        let c = calendar.dateComponents([.year, .month, .day, .hour, .minute], from: date)
        return String(format: "%04d-%02d-%02d %02d:%02d", c.year!, c.month!, c.day!, c.hour!, c.minute!)
    }
}

/// `~/.perch/inbox.md`: append-only. perchd absorbs every `- [ ] title` line and removes it;
/// anything else in the file is left alone.
public enum Inbox {
    public struct Parsed: Equatable {
        public var entries: [String]
        /// The file's new contents: every line that was not absorbed (empty if only blank lines remain).
        public var remainder: String
        /// The last line is an entry without its newline, left in `remainder`: it may still be being written.
        public var pending = false
    }

    /// `absorbUnterminated`: take a last entry that has no newline too (the file has stopped changing, so it is
    /// an editor that saves without a final newline, not a line half written).
    public static func parse(_ text: String, absorbUnterminated: Bool = false) -> Parsed {
        var entries: [String] = []
        var kept: [Substring] = []
        var pending = false
        let lines = text.split(separator: "\n", omittingEmptySubsequences: false)
        for (index, line) in lines.enumerated() {
            // The last piece has no newline after it (empty when the text ends with one).
            if let entry = entry(in: line), absorbUnterminated || index < lines.count - 1 {
                if !entry.isEmpty { entries.append(entry) }
            } else {
                if entry(in: line).map({ !$0.isEmpty }) == true { pending = true }
                kept.append(line)
            }
        }
        let remainder = kept.joined(separator: "\n")
        return Parsed(entries: entries,
                      remainder: remainder.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? "" : remainder,
                      pending: pending)
    }

    /// The text after `- [ ] ` / `* [ ] `, or nil if the line is not an open checkbox.
    private static func entry(in line: Substring) -> String? {
        let trimmed = line.drop { $0 == " " || $0 == "\t" }
        for prefix in ["- [ ] ", "* [ ] ", "- [ ]", "* [ ]"] where trimmed.hasPrefix(prefix) {
            return trimmed.dropFirst(prefix.count).trimmingCharacters(in: .whitespacesAndNewlines)
        }
        return nil
    }
}

/// One-line entry like "回复 X 的邮件 @15:00": a trailing `@…` / `+…` token that parses as a due time
/// becomes `due`; otherwise the whole text is the title. Used by the inbox and (M2) quick entry.
public enum QuickEntry {
    public static func parse(_ text: String, now: Date = Date(), calendar: Calendar = .current) -> (title: String, due: Date?) {
        let trimmed = text.trimmingCharacters(in: .whitespaces)
        guard let space = trimmed.lastIndex(of: " ") else { return (trimmed, nil) }
        let token = trimmed[trimmed.index(after: space)...]
        guard token.hasPrefix("@") || token.hasPrefix("+"),
              let due = try? DueParser.parse(String(token), now: now, calendar: calendar) else { return (trimmed, nil) }
        let title = trimmed[..<space].trimmingCharacters(in: .whitespaces)
        return title.isEmpty ? (trimmed, nil) : (title, due)
    }
}
